Group1-Router1:
    hostname: 10.99.1.1
    platform: 'ios'
    username: apnic
    password: training

Group2-Router1:
    hostname: 10.99.2.1
    platform: 'ios'
    username: apnic
    password: training

