EVE_1 = "192.168.20.12"
EVE_USER = "admin"
EVE_PASSWORD = "eve"
ROUTER_USER = "apnic"
ROUTER_PASSWORD = "training"
ROUTER_TIMEOUT = 6
#PYTHON_PATH = "/usr/bin/python3" # For UbuntuLinux
PYTHON_PATH = "python" # For Windows10
APP_SECRET_KEY = "your_secret_key"
EVE_1_IDLE_PC = "0x63188e04"
